### ISSUE TITLE
Mobile - Sticky CTA Buttons

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#444] opened 2024-11-06 20:58 UTC
Mobile sticky CTA buttons are missing on EDS site. These should be present across the entire site. See home page for example on mobile - https://www.shredit.com/en-us

There are a few template which do not render this on mobile because they have another mobile sticky option. This relates to our new Marketing Page Template - e.g. https://www.shredit.com/en-us/marketing/shred-it-document-destruction-inline

![image](https://github.com/user-attachments/assets/0411bc23-3dbd-4d84-bcaf-70bbb0915fc6)

**Comment by bstopp** [comment] 2024-11-19 15:06
This has been addressed by fixing the root cause (other blocks).

**Closed by bstopp** 2024-11-19 15:06 UTC
