### ISSUE TITLE
New SEM Page - Shredded Paper Background Not Showing

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#637] opened 2024-12-13 16:53 UTC
The shredded paper background is not showing on https://stage-us.shredit.com/en-us/email/paper-shredding-services?nocache=1734108599025

![image](https://github.com/user-attachments/assets/8e99ab2c-952e-4107-8c80-c43d4b004d63)

The style is selected in the metadata

![image](https://github.com/user-attachments/assets/ea8b97cf-b583-4180-8027-fa2810f93e09)

**Comment by jindaliiita** [comment] 2024-12-19 13:21
Its not reproducible on https://main--shredit--stericycle.aem.live/en-us/email/paper-shredding-services

@kronnox Do you have any idea why the image is present on https://main--shredit--stericycle.aem.live/images/sid-shreded-paper-background.png but not on https://stage-us.shredit.com/images/sid-shreded-paper-background.png

**Comment by kronnox** [comment] 2024-12-20 09:20
That's weird indeed. From a gut feeling I would say it's probably an issue with the current CDN configuration, but not 100% sure @ericvangeem

**Comment by ericvangeem** [comment] 2024-12-20 14:32
@kronnox I can confirm this is a CDN issue, looks like this `/images` root path is new and is not currently included in the CDN path routing rules. I will update this.

**Comment by ericvangeem** [comment] 2024-12-20 15:10
@colinvlasak CDN config is now updated in Stage and this URL should be working again, please double check: https://stage-us.shredit.com/en-us/email/paper-shredding-services

@kronnox just for your reference, these are the current URL paths we have configured in CDN to route to EDS: `matches: "^^(/en-us.*|/forms/.*|/scripts/.*|/templates/.*|/ext-libs/.*|/styles/.*|/fonts/.*|/images/.*|/blocks/.*|/icons/.*|.*/media_.*|/favicon.ico|/query-index.json|/schemas.json)"`

**Comment by colinvlasak** [comment] 2024-12-20 15:14
@ericvangeem confirming that I am seeing it on https://stage-us.shredit.com/en-us/email/paper-shredding-services

**Comment by colinvlasak** [comment] 2024-12-20 18:41
@ericvangeem great, thanks for the additional details.

**Comment by jindaliiita** [comment] 2024-12-23 05:50
Closing this as its now resolved

**Closed by jindaliiita** 2024-12-23 05:50 UTC
