### ISSUE TITLE
Fragments within Components/Modals

### ISSUE THREAD

**Issue by rwcsrichardspencer** [aemsites/stericycle-shared#348] opened 2024-10-11 19:54 UTC
@vdua @jalagari we'd like have the ability to put fragments & forms within columns and modals.
For example we have Columns table and in the 2nd column, we'd like to add a fragment and/or form.

**Comment by MarquiseRosier** [comment] 2024-10-22 13:55
@ravise5 I believe this is where this capability is being tracked.

**Comment by ravise5** [comment] 2024-11-29 09:23
@MarquiseRosier This is a duplicate of #514.  Also we have already added the support of fragments and forms in modals hence marking this as complete.

**Closed by ravise5** 2024-11-29 09:23 UTC
Labels: forms
